import{S as y,i as m,a as L}from"./assets/vendor-b52d9f5e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const b="https://pixabay.com/api",v="42087776-9136d7523d21dc11bf8e1a72d",q=document.querySelector(".form"),c=document.querySelector(".gallery"),d=document.querySelector(".loader"),i=document.querySelector(".button");q.addEventListener("submit",k);d.classList.remove("loader");const h=new y(".gallery a",{captionsData:"alt",captionDelay:250}),n={query:"",page:1,per_page:40,maxPage:0};async function k(s){s.preventDefault(),c.innerHTML="";const o=s.currentTarget;if(n.query=o.elements.query.value.trim(),d.classList.add("loader"),i.classList.add("is-hidden"),!!n.query)try{const{data:r}=await p(n);console.log(r);let a="";const e=r.hits;for(const u of e)a+=g(u);e.length===0&&m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});const t=r.totalHits;n.maxPage=Math.ceil(t/n.per_page),c.innerHTML=a;const l=c.firstElementChild.getBoundingClientRect();scrollBy({top:l.height,behavior:"smooth"}),d.classList.remove("loader"),e.length>0&&e.length!==t?(i.addEventListener("click",f),i.classList.remove("is-hidden")):i.classList.add("is-hidden"),h.refresh()}catch(r){console.log(r)}finally{o.reset()}}async function f(){n.page+=1,d.classList.add("loader"),i.classList.add("is-hidden");try{const{data:s}=await p(n);console.log(s);let o="";const r=s.hits;for(const e of r)o+=g(e);c.innerHTML+=o;const a=c.firstElementChild.getBoundingClientRect();scrollBy({top:a.height,behavior:"smooth"}),h.refresh()}catch(s){console.log(s)}finally{d.classList.remove("loader"),i.classList.remove("is-hidden")}n.page===n.maxPage&&(i.classList.add("is-hidden"),m.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),i.removeEventListener("click",f))}async function p({query:s,page:o=1,per_page:r}){try{return await L.get(`${b}/?`,{params:{key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:r}})}catch(a){console.log(a)}}function g({webformatURL:s,largeImageURL:o,tags:r,likes:a,views:e,comments:t,downloads:l}){return` <li class="gallery-item">
    <a class="gallery-link" href=${o}>
      <img
        class="gallery-image"
        src=${s}
        alt=${r}
        >
  
        <p>Likes<br> ${a}</p>
        <p>Views<br> ${e}</p>
        <p>Comments<br> ${t}</p>
        <p>Downloads<br> ${l}</p>   
    </a>
  </li>`}
//# sourceMappingURL=commonHelpers.js.map
